include: package:flutter_lints/flutter.yaml


analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    deprecated_member_use_from_same_package: ignore
    unnecessary_null_comparison: ignore
    must_be_immutable: warning
    no_leading_underscores_for_local_identifiers: ignore
    use_build_context_synchronously: ignore

linter:

  rules:
    avoid_print: false
    prefer_single_quotes: true 
    avoid_empty_else: true
    