name: finca
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  icons_launcher: ^1.2.1
  animated_splash_screen: ^1.2.0
  sliding_clipped_nav_bar:
    git:
      url: https://github.com/watery-desert/sliding_clipped_nav_bar
  splashscreen:
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  calendar_appbar: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter_icons:
  image_path: 'assets/logo_finca.png'
  ios: true
  android: true

flutter:

  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: MusticaPro
      fonts:
        - asset: fonts/MusticaPro-SemiBold.otf
        
  

